version: "3"

services:
  app-dev:
    image: node:20
    depends_on:
      - graphdb
      - react
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
    command: sh -c "cd /app && yarn && yarn start"
